### ISSUE TITLE
Вопрос #1

### ISSUE THREAD

**Issue by serge2016** [guzelfey/docker_SHLB#1]
https://github.com/guzelfey/docker_SHLB/blob/98f972c5a630a031b93a9c0e6f77224cd256cf11/Dockerfile#L44

точно ли нужно указывать место до исходников, а не до того места, куда установлена программа?

и все же стоит в явном виде указывать, куда ставить каждую программу..

**Comment by guzelfey** [comment]
Спасибо! Места установки поправлены.
